package edu.unipampa.laboratoriovirologia.domain.enumeration;

public enum TipoExame {
    SORONEUTRALIZACAO("SORONEUTRALIZACAO"),
    ENSAIO_IMUNOABSORCAO_ENZIMATICA("ENSAIO_IMUNOABSORCAO_ENZIMATICA"),
    REACAO_CADEIA_POLIMERASE("REACAO_CADEIA_POLIMERASE"),
    IMUNOCROMATOGRAFIA("IMUNOCROMATOGRAFIA"),
    IMUNOFLUORESCENCIA("IMUNOFLUORESCENCIA"),
    INIBICAO_HEMAGLUTINACAO("INIBICAO_HEMAGLUTINACAO"),
    ISOLAMENTO_VIRAL("ISOLAMENTO_VIRAL"),
    IMUNODIFUSAO_GEL_AGAR("IMUNODIFUSAO_GEL_AGAR"),
    MICROSCOPIA_ELETRONICA("MICROSCOPIA_ELETRONICA"),
    VACINA_AUTOGENA("VACINA_AUTOGENA");

    private final String valor;
    
    TipoExame(String valorOpcao){
        valor = valorOpcao;
    }
    public String getValor(){
        return valor;
    }
}
