package edu.unipampa.laboratoriovirologia.domain.enumeration;

public enum TipoExame {
    SORONEUTRALIZACAO,
    ENSAIO_IMUNOABSORCAO_ENZIMATICA,
    REACAO_CADEIA_POLIMERASE,
    IMUNOCROMATOGRAFIA,
    IMUNOFLUORESCENCIA,
    INIBICAO_HEMAGLUTINACAO,
    ISOLAMENTO_VIRAL,
    IMUNODIFUSAO_GEL_AGAR,
    MICROSCOPIA_ELETRONICA
}
